# Default values for pod-aad-identity-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
registry: podid.azurecr.io

rbac:
  enabled: false

mic:
  adminClientID: "1d59908a-66f5-4a41-ae9a-8a4da14c6869"

azureIdentity:
  enabled: true # enabled/disable deployment of azure identity and binding
  name: "azure-identity"
  type: 0 # type 0: MSI, type 1: Service Principal
  resourceID: "/subscriptions/27b750cd-ed43-42fd-9044-8d75e124ae55/resourceGroups/feshi-k8s/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demoapp" # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
  clientID: "02de69eb-2f0b-409f-a667-8d5dc7e10855"

azureIdentityBinding:
  name: "azure-identity-binding"
  selector: "demoapp" # demo

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
